name: "Hello Action"
description: "Greet someone"
author: bigirwak@gmail.com

inputs:
  MY_NAME:
     description: "Who to greet"
     required: true
     default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"